local M = {}

M.KEY_PRESS = 2
M.BUTTON_PRESS = 4
M.BUTTON_RELEASE = 5
M.MOTION_NOTIFY = 6
M.EXPOSE = 12

M.KEY_PRESS_MASK = 0x1
M.KEY_RELEASE_MASK = 0x2
M.BUTTON_PRESS_MASK = 0x4
M.BUTTON_RELEASE_MASK = 0x8
M.POINTER_MOTION_MASK = 0x40
M.EXPOSURE_MASK = 0x8000

M.INPUT_MASK_BASE = M.EXPOSURE_MASK + M.BUTTON_PRESS_MASK + M.BUTTON_RELEASE_MASK + M.POINTER_MOTION_MASK
M.INPUT_MASK_KBD = M.INPUT_MASK_BASE + M.KEY_PRESS_MASK + M.KEY_RELEASE_MASK

M.WHEEL_UP = 4
M.WHEEL_DOWN = 5

M.SHIFT_MASK = 0x1
M.LOCK_MASK = 0x2
M.CONTROL_MASK = 0x4
M.MOD1_MASK = 0x8
M.MOD2_MASK = 0x10
M.MOD3_MASK = 0x20
M.MOD4_MASK = 0x40
M.MOD5_MASK = 0x80

M.LOCK_BITS = bit.bor(M.LOCK_MASK, M.MOD2_MASK)

M.CW_BACK_PIXMAP = 0x1
M.CW_BACK_PIXEL = 0x2
M.CW_BORDER_PIXEL = 0x8
M.CW_OVERRIDE_REDIRECT = 0x200

M.MOD_NAMES = {
  shift = M.SHIFT_MASK,
  lock = M.LOCK_MASK,
  caps = M.LOCK_MASK,
  ctrl = M.CONTROL_MASK,
  control = M.CONTROL_MASK,
  alt = M.MOD1_MASK,
  mod1 = M.MOD1_MASK,
  mod2 = M.MOD2_MASK,
  num = M.MOD2_MASK,
  mod3 = M.MOD3_MASK,
  super = M.MOD4_MASK,
  mod4 = M.MOD4_MASK,
  win = M.MOD4_MASK,
  cmd = M.MOD4_MASK,
  meta = M.MOD4_MASK,
  mod5 = M.MOD5_MASK,
  shiftmask = M.SHIFT_MASK,
  lockmask = M.LOCK_MASK,
  controlmask = M.CONTROL_MASK,
  mod1mask = M.MOD1_MASK,
  mod2mask = M.MOD2_MASK,
  mod3mask = M.MOD3_MASK,
  mod4mask = M.MOD4_MASK,
  mod5mask = M.MOD5_MASK,
}

return M
